format_version: 10
pipelines:
  pokedex-app:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      pokedex-app:
        git: https://github.com/lariskovski/pokedex
        username: ''
        shallow_clone: false
        auto_update: false
        branch: gocd-test
    stages:
    - build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          docker-build:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - Docker Build...
                command: echo
                run_if: passed
