service: pokedex
 
provider:
  name: aws
  runtime: go1.x
  memorySize: 128 # optional, in MB, default is 1024
  environment:
    MONGODB_URI: ${env:MONGODB_URI}

package:
 exclude:
   - ./**
 include:
   - ./bin/**
 
functions:
  get:
    handler: bin/get
    events:
      - http:
          path: pokemons
          method: get
          request:
            parameters:
              querystrings:
                name: false
          # authorizer:
          #   arn: ${env:LAMBDA_AUTHORIZER_ARN}
  post:
    handler: bin/post
    events:
      - http:
          path: pokemons
          method: post
          # authorizer:
          #   arn: ${env:LAMBDA_AUTHORIZER_ARN}
  put:
    handler: bin/put
    events:
      - http:
          path: pokemons/{name}
          method: put
          request:
            parameters:
              paths:
                name: true
          # authorizer:
          #   arn: ${env:LAMBDA_AUTHORIZER_ARN}
  delete:
    handler: bin/delete
    events:
      - http:
          path: pokemons/{name}
          method: delete
          request:
            parameters:
              paths:
                name: true
          # authorizer:
          #   arn: ${env:LAMBDA_AUTHORIZER_ARN}
